---
- name: Install Counter-Strike 1.6 server
  hosts: cs16
  become: true
  roles:
    - role: cs16_server
      vars:
        cs16_hostname: "LenMail CS 1.6 Fun Server | Classics, Bots & RTV"
        cs16_maxplayers: 16
        cs16_start_map: de_dust2
        cs16_bot_fill_players: 10
        cs16_manage_fail2ban_whitelist: true
        cs16_admin_steamids:
          - steamid: "STEAM_0:1:44263"
            comment: "OnkelDom"
          - steamid: "STEAM_0:0:44840329"
            comment: "sm9nsen"
