---
- name: Reload systemd
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: Restart cs16
  ansible.builtin.systemd_service:
    name: cs16.service
    state: restarted
    daemon_reload: true

